ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"

plugins=(git virtualenvwrapper pip)

source $ZSH/oh-my-zsh.sh

export EDITOR=/usr/bin/vim

# virtualenvwrapper related
export WORKON_HOME=$HOME/envs
export VIRTUALENV_USE_DISTRIBUTE=1
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true
export PROJECT_HOME=$HOME/work/pbs
source /usr/local/bin/virtualenvwrapper.sh

